server:
  address: 127.0.0.1
  port: 9000

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot
          group: comments
          content-type: application/json
        output:
          destination: learning-spring-boot
  application:
    name: comments

management:
  context-path: /